#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OnlineFridge.Resource", IsApplication=true)]

namespace OnlineFridge
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int bg = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int blue = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int custom_theme_background = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int customtheme_background = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Splash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060017
			public const int accountDel = 2131099671;
			
			// aapt resource value: 0x7f060013
			public const int addProduct = 2131099667;
			
			// aapt resource value: 0x7f060021
			public const int badPass = 2131099681;
			
			// aapt resource value: 0x7f060011
			public const int button1 = 2131099665;
			
			// aapt resource value: 0x7f06001c
			public const int button2 = 2131099676;
			
			// aapt resource value: 0x7f060022
			public const int buttonLogin = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int buttonRegister = 2131099683;
			
			// aapt resource value: 0x7f06000d
			public const int date_display = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int date_display1 = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int date_select_button = 2131099663;
			
			// aapt resource value: 0x7f060007
			public const int dekagramy = 2131099655;
			
			// aapt resource value: 0x7f060014
			public const int editAccount = 2131099668;
			
			// aapt resource value: 0x7f060001
			public const int editText1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int editText2 = 2131099651;
			
			// aapt resource value: 0x7f060025
			public const int email = 2131099685;
			
			// aapt resource value: 0x7f060028
			public const int error = 2131099688;
			
			// aapt resource value: 0x7f060012
			public const int fridgeContent = 2131099666;
			
			// aapt resource value: 0x7f060008
			public const int gramy = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int kilogramy = 2131099654;
			
			// aapt resource value: 0x7f060029
			public const int linearLayout1 = 2131099689;
			
			// aapt resource value: 0x7f060009
			public const int litry = 2131099657;
			
			// aapt resource value: 0x7f060015
			public const int logout = 2131099669;
			
			// aapt resource value: 0x7f06000a
			public const int mililitry = 2131099658;
			
			// aapt resource value: 0x7f060027
			public const int pass = 2131099687;
			
			// aapt resource value: 0x7f060016
			public const int passChange = 2131099670;
			
			// aapt resource value: 0x7f060020
			public const int password = 2131099680;
			
			// aapt resource value: 0x7f060018
			public const int productListView = 2131099672;
			
			// aapt resource value: 0x7f06002a
			public const int produkt = 2131099690;
			
			// aapt resource value: 0x7f060005
			public const int radioGroup1 = 2131099653;
			
			// aapt resource value: 0x7f060010
			public const int space1 = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int space2 = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int sztuki = 2131099659;
			
			// aapt resource value: 0x7f060024
			public const int textEmail = 2131099684;
			
			// aapt resource value: 0x7f06001d
			public const int textLogin = 2131099677;
			
			// aapt resource value: 0x7f060026
			public const int textPass = 2131099686;
			
			// aapt resource value: 0x7f06001f
			public const int textPassword = 2131099679;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int textView3 = 2131099652;
			
			// aapt resource value: 0x7f06002c
			public const int textView4 = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int textView5 = 2131099693;
			
			// aapt resource value: 0x7f06001a
			public const int txtCount = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int txtExpDate = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int txtName = 2131099673;
			
			// aapt resource value: 0x7f06002b
			public const int txtProduct = 2131099691;
			
			// aapt resource value: 0x7f06001e
			public const int username = 2131099678;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddProduct = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AfterLogin = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateShopList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditAccount = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FridgeContent = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int listview_row = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int OfflineMode = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int OnlineFridgeContent = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int OnlineMode = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Register = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int UpdateProduct = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int CustomTheme = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int CustomTheme2 = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
